jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./HairDrop-frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Debug
        run: ls -la
        working-directory: ./HairDrop-frontend
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
        working-directory: ./HairDrop-frontend
      - name: Build
        run: npm run build
        working-directory: ./HairDrop-frontend
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Move 404 page to dist
        run: mv 404.html dist
        working-directory: ./HairDrop-frontend
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
