# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: HairDrop-frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      # Set up Node with explicit working-directory and cache location
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'  # Enable npm caching
          cache-dependency-path: ./HairDrop-frontend/package-lock.json  # Set the correct path for the lock file

      # Install dependencies
      - name: Install dependencies
        run: npm ci
        working-directory: ./HairDrop-frontend

      # Build the project
      - name: Build
        run: npm run build
        working-directory: ./HairDrop-frontend

      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Move 404 page to dist
      - name: Move 404 page to dist
        run: mv 404.html dist
        working-directory: ./HairDrop-frontend

      # Upload the dist folder to GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './HairDrop-frontend/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
