name: Java CI

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  workflow_dispatch: # manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get the code from the repository
      uses: actions/checkout@v4
      with:
        ref: 'main'
        fetch-depth: 0 

    - name: Create error logs directory
      run: mkdir -p error-logs

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Set execute permissions on build scripts
      run: chmod +x bin/generate-plantuml-diagrams.sh || true

    - name: Install Graphviz
      run: sudo apt-get install -y graphviz

    - name: Set up Git user
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Update .svg
      run: ./bin/generate-plantuml-diagrams.sh
      
    - name: Add SVG files
      run: git add *.svg

    - name: Commit and push if there are changes
      run: |
        if ! git diff --cached --quiet; then
          git commit -m "ref #36 Update diagrams"
          git push origin HEAD:main
        else
          echo "No changes to SVG files"
        fi